"""Seed service for glossary entries.

Seeds financial terms across three categories: dcf, ratios, and profile.
Uses idempotent check-then-insert/update pattern.
"""

import logging

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.shared import Glossary

logger = logging.getLogger(__name__)

# (technical_term, display_label, technical_label, tooltip, category)
GLOSSARY_ENTRIES: list[tuple[str, str, str, str, str]] = [
    # --- DCF (15) ---
    (
        "wacc",
        "Weighted Average Cost of Capital",
        "WACC",
        "The blended rate a company must earn on its existing assets to satisfy both debt holders and equity investors.",
        "dcf",
    ),
    (
        "fcff",
        "Free Cash Flow to the Firm",
        "FCFF",
        "Cash generated by operations after reinvestment needs, available to all capital providers (debt + equity).",
        "dcf",
    ),
    (
        "terminal_value",
        "Terminal Value",
        "TV",
        "The estimated value of a business beyond the explicit forecast period, assuming a stable growth rate in perpetuity.",
        "dcf",
    ),
    (
        "beta",
        "Beta",
        "Beta",
        "A measure of a stock's volatility relative to the overall market. A beta of 1.0 means the stock moves with the market.",
        "dcf",
    ),
    (
        "equity_risk_premium",
        "Equity Risk Premium",
        "ERP",
        "The excess return investors demand for holding equities over risk-free government bonds.",
        "dcf",
    ),
    (
        "cost_of_equity",
        "Cost of Equity",
        "Ke",
        "The return rate shareholders require to compensate for the risk of investing in a company's stock.",
        "dcf",
    ),
    (
        "cost_of_debt",
        "Cost of Debt",
        "Kd",
        "The effective rate a company pays on its borrowed funds, typically after accounting for the tax shield.",
        "dcf",
    ),
    (
        "risk_free_rate",
        "Risk-Free Rate",
        "Rf",
        "The theoretical return on an investment with zero risk, usually proxied by the 10-year US Treasury yield.",
        "dcf",
    ),
    (
        "terminal_growth",
        "Terminal Growth Rate",
        "g",
        "The perpetual growth rate applied to free cash flows after the forecast period; should not exceed long-run GDP growth.",
        "dcf",
    ),
    (
        "discount_rate",
        "Discount Rate",
        "r",
        "The rate used to convert future cash flows into their present value; typically equals WACC in a DCF model.",
        "dcf",
    ),
    (
        "enterprise_value",
        "Enterprise Value",
        "EV",
        "The total value of a business including equity and net debt, representing the theoretical takeover price.",
        "dcf",
    ),
    (
        "intrinsic_value",
        "Intrinsic Value",
        "IV",
        "The estimated per-share value derived from a DCF model, independent of the current market price.",
        "dcf",
    ),
    (
        "reinvestment_rate",
        "Reinvestment Rate",
        "RR",
        "The fraction of after-tax operating income a company plows back into the business to sustain growth.",
        "dcf",
    ),
    (
        "return_on_capital",
        "Return on Capital",
        "ROC",
        "A measure of how efficiently a company generates profits from its invested capital (debt + equity).",
        "dcf",
    ),
    (
        "sensitivity_analysis",
        "Sensitivity Analysis",
        "Sensitivity",
        "A table showing how intrinsic value changes when key inputs (like WACC or growth rate) are varied.",
        "dcf",
    ),
    # --- Ratios (12) ---
    (
        "pe_ratio",
        "Price-to-Earnings Ratio",
        "P/E",
        "Compares a company's share price to its earnings per share; a high P/E may signal growth expectations.",
        "ratios",
    ),
    (
        "pb_ratio",
        "Price-to-Book Ratio",
        "P/B",
        "Compares market capitalisation to book value of equity; values below 1.0 may indicate undervaluation.",
        "ratios",
    ),
    (
        "ps_ratio",
        "Price-to-Sales Ratio",
        "P/S",
        "Compares market capitalisation to total revenue; useful for valuing companies with no earnings.",
        "ratios",
    ),
    (
        "ev_to_ebitda",
        "Enterprise Value to EBITDA",
        "EV/EBITDA",
        "A capital-structure-neutral valuation multiple comparing total firm value to operating cash earnings.",
        "ratios",
    ),
    (
        "debt_to_equity",
        "Debt-to-Equity Ratio",
        "D/E",
        "Measures financial leverage by comparing total debt to shareholders' equity; higher values imply more leverage.",
        "ratios",
    ),
    (
        "current_ratio",
        "Current Ratio",
        "CR",
        "Current assets divided by current liabilities; values above 1.0 suggest the company can cover short-term obligations.",
        "ratios",
    ),
    (
        "roe",
        "Return on Equity",
        "ROE",
        "Net income divided by shareholders' equity; measures how efficiently a company generates profit from equity capital.",
        "ratios",
    ),
    (
        "roa",
        "Return on Assets",
        "ROA",
        "Net income divided by total assets; indicates how effectively a company uses its asset base to generate profit.",
        "ratios",
    ),
    (
        "gross_margin",
        "Gross Margin",
        "GM",
        "Gross profit as a percentage of revenue; reflects pricing power and production efficiency.",
        "ratios",
    ),
    (
        "operating_margin",
        "Operating Margin",
        "OM",
        "Operating income as a percentage of revenue; shows profitability from core operations before interest and taxes.",
        "ratios",
    ),
    (
        "net_margin",
        "Net Margin",
        "NM",
        "Net income as a percentage of revenue; the bottom-line profit kept from each dollar of sales.",
        "ratios",
    ),
    (
        "interest_coverage",
        "Interest Coverage Ratio",
        "ICR",
        "Operating income divided by interest expense; indicates how easily a company can service its debt obligations.",
        "ratios",
    ),
    # --- Profile (4) ---
    (
        "market_cap",
        "Market Capitalisation",
        "Market Cap",
        "The total market value of a company's outstanding shares, calculated as share price times shares outstanding.",
        "profile",
    ),
    (
        "dividend_yield",
        "Dividend Yield",
        "Div Yield",
        "Annual dividends per share divided by the share price, expressed as a percentage.",
        "profile",
    ),
    (
        "shares_outstanding",
        "Shares Outstanding",
        "Shares Out",
        "The total number of shares currently held by all shareholders, including restricted shares.",
        "profile",
    ),
    (
        "ttm",
        "Trailing Twelve Months",
        "TTM",
        "A rolling 12-month period used to evaluate financial performance using the most recent data available.",
        "profile",
    ),
]


async def seed_glossary(session: AsyncSession) -> int:
    """Seed glossary entries into the database.

    Uses a check-then-update/insert pattern keyed on technical_term to ensure
    idempotent operation. Existing rows are updated to match the seed data;
    new rows are inserted.

    Returns the total number of entries seeded (inserted + updated).
    """
    result = await session.execute(select(Glossary))
    existing = {entry.technical_term: entry for entry in result.scalars().all()}

    inserted = 0
    updated = 0

    for (
        technical_term,
        display_label,
        technical_label,
        tooltip,
        category,
    ) in GLOSSARY_ENTRIES:
        if technical_term in existing:
            entry = existing[technical_term]
            entry.display_label = display_label
            entry.technical_label = technical_label
            entry.tooltip = tooltip
            entry.category = category
            updated += 1
        else:
            session.add(
                Glossary(
                    technical_term=technical_term,
                    display_label=display_label,
                    technical_label=technical_label,
                    tooltip=tooltip,
                    category=category,
                )
            )
            inserted += 1

    await session.commit()

    total = inserted + updated
    logger.info(
        "Glossary seeded: %d inserted, %d updated, %d total",
        inserted,
        updated,
        total,
    )
    return total
