"""create all 19 tables

Revision ID: 057f02f41cd7
Revises: 
Create Date: 2026-02-19 22:42:23.044051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '057f02f41cd7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_risk_premiums',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('moody_rating', sa.String(length=10), nullable=True),
    sa.Column('default_spread', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('equity_risk_premium', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('country_risk_premium', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country')
    )
    op.create_table('damodaran_industries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('industry_name', sa.String(length=150), nullable=False),
    sa.Column('num_firms', sa.BigInteger(), nullable=True),
    sa.Column('unlevered_beta', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_effective_tax_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_debt_to_equity', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_operating_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_roc', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_reinvestment_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cost_of_capital', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fundamental_growth_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry_name')
    )
    op.create_table('dashboard_tickers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('data_source', sa.String(length=30), nullable=False),
    sa.Column('display_format', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dashboard_tickers_category_order', 'dashboard_tickers', ['category', 'display_order'], unique=False)
    op.create_index('ix_dashboard_tickers_is_active', 'dashboard_tickers', ['is_active'], unique=False)
    op.create_table('default_spreads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('spread_over_treasury', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rating')
    )
    op.create_table('fred_series',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'observation_date', name='uq_fred_series_composite')
    )
    op.create_index('ix_fred_series_composite', 'fred_series', ['series_id', 'observation_date'], unique=False)
    op.create_table('glossary',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('technical_term', sa.String(length=50), nullable=False),
    sa.Column('display_label', sa.String(length=200), nullable=False),
    sa.Column('technical_label', sa.String(length=50), nullable=False),
    sa.Column('tooltip', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('learn_more_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technical_term')
    )
    op.create_index(op.f('ix_glossary_category'), 'glossary', ['category'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('ix_stocks_sector_industry', 'stocks', ['sector', 'industry'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('clerk_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id')
    )
    op.create_table('dcf_valuations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('damodaran_industry_id', sa.BigInteger(), nullable=True),
    sa.Column('source_fiscal_date', sa.Date(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_type', sa.String(length=10), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('run_name', sa.String(length=200), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['damodaran_industry_id'], ['damodaran_industries.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dcf_valuations_stock_default', 'dcf_valuations', ['stock_id', 'is_default'], unique=False)
    op.create_index('ix_dcf_valuations_stock_user', 'dcf_valuations', ['stock_id', 'user_id'], unique=False)
    op.create_index('ix_dcf_valuations_user_saved', 'dcf_valuations', ['user_id', 'is_saved'], unique=False)
    op.create_table('dividends',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dividends_stock_ex_date', 'dividends', ['stock_id', 'ex_date'], unique=False)
    op.create_table('earnings_calendar',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('fiscal_quarter', sa.String(length=10), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_earnings_calendar_stock_report_date', 'earnings_calendar', ['stock_id', 'report_date'], unique=False)
    op.create_table('financial_statements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('statement_type', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('fiscal_date', sa.Date(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'statement_type', 'period', 'fiscal_date', name='uq_financial_statements_composite')
    )
    op.create_index('ix_financial_statements_composite', 'financial_statements', ['stock_id', 'statement_type', 'period', 'fiscal_date'], unique=False)
    op.create_index(op.f('ix_financial_statements_stock_id'), 'financial_statements', ['stock_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='uq_price_history_stock_date')
    )
    op.create_index('ix_price_history_stock_date', 'price_history', ['stock_id', 'date'], unique=False)
    op.create_table('sector_mapping',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('twelvedata_sector', sa.String(length=100), nullable=False),
    sa.Column('twelvedata_industry', sa.String(length=100), nullable=False),
    sa.Column('damodaran_industry_id', sa.BigInteger(), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('manually_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['damodaran_industry_id'], ['damodaran_industries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twelvedata_sector', 'twelvedata_industry', name='uq_sector_mapping_composite')
    )
    op.create_index('ix_sector_mapping_composite', 'sector_mapping', ['twelvedata_sector', 'twelvedata_industry'], unique=False)
    op.create_table('stock_splits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ratio_from', sa.Integer(), nullable=False),
    sa.Column('ratio_to', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_splits_stock_date', 'stock_splits', ['stock_id', 'date'], unique=False)
    op.create_table('dcf_audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dcf_valuation_id', sa.BigInteger(), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dcf_valuation_id'], ['dcf_valuations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dcf_audit_log_dcf_valuation_id'), 'dcf_audit_log', ['dcf_valuation_id'], unique=False)
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('cost_basis_per_share', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'stock_id', name='uq_portfolio_holdings_composite')
    )
    op.create_index('ix_portfolio_holdings_portfolio_stock', 'portfolio_holdings', ['portfolio_id', 'stock_id'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_cost_basis', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_gain_loss', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('holdings_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'date', name='uq_portfolio_snapshots_composite')
    )
    op.create_index('ix_portfolio_snapshots_portfolio_date', 'portfolio_snapshots', ['portfolio_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_portfolio_snapshots_portfolio_date', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index('ix_portfolio_holdings_portfolio_stock', table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_index(op.f('ix_dcf_audit_log_dcf_valuation_id'), table_name='dcf_audit_log')
    op.drop_table('dcf_audit_log')
    op.drop_index('ix_stock_splits_stock_date', table_name='stock_splits')
    op.drop_table('stock_splits')
    op.drop_index('ix_sector_mapping_composite', table_name='sector_mapping')
    op.drop_table('sector_mapping')
    op.drop_index('ix_price_history_stock_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_financial_statements_stock_id'), table_name='financial_statements')
    op.drop_index('ix_financial_statements_composite', table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index('ix_earnings_calendar_stock_report_date', table_name='earnings_calendar')
    op.drop_table('earnings_calendar')
    op.drop_index('ix_dividends_stock_ex_date', table_name='dividends')
    op.drop_table('dividends')
    op.drop_index('ix_dcf_valuations_user_saved', table_name='dcf_valuations')
    op.drop_index('ix_dcf_valuations_stock_user', table_name='dcf_valuations')
    op.drop_index('ix_dcf_valuations_stock_default', table_name='dcf_valuations')
    op.drop_table('dcf_valuations')
    op.drop_table('users')
    op.drop_index('ix_stocks_sector_industry', table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_glossary_category'), table_name='glossary')
    op.drop_table('glossary')
    op.drop_index('ix_fred_series_composite', table_name='fred_series')
    op.drop_table('fred_series')
    op.drop_table('default_spreads')
    op.drop_index('ix_dashboard_tickers_is_active', table_name='dashboard_tickers')
    op.drop_index('ix_dashboard_tickers_category_order', table_name='dashboard_tickers')
    op.drop_table('dashboard_tickers')
    op.drop_table('damodaran_industries')
    op.drop_table('country_risk_premiums')
    # ### end Alembic commands ###
