export interface GlossaryEntry {
  technical_term: string;
  display_label: string;
  technical_label: string;
  tooltip: string;
  category: string;
  learn_more_url: string | null;
}

/**
 * Hardcoded glossary of financial terms.
 * Will be replaced with build-time fetch later.
 */
export const glossary: Record<string, GlossaryEntry> = {
  // ---------------------------------------------------------------------------
  // DCF terms
  // ---------------------------------------------------------------------------
  wacc: {
    technical_term: "wacc",
    display_label: "Cost of Capital",
    technical_label: "WACC",
    tooltip:
      "Weighted Average Cost of Capital. The blended rate a company must earn on its assets to satisfy both debt holders and equity investors.",
    category: "dcf",
    learn_more_url: null,
  },
  fcff: {
    technical_term: "fcff",
    display_label: "Free Cash Flow to Firm",
    technical_label: "FCFF",
    tooltip:
      "Cash generated by operations after reinvestment, available to all capital providers (debt and equity).",
    category: "dcf",
    learn_more_url: null,
  },
  terminal_value: {
    technical_term: "terminal_value",
    display_label: "Terminal Value",
    technical_label: "Terminal Value",
    tooltip:
      "The estimated value of all cash flows beyond the explicit forecast period, assuming stable growth forever.",
    category: "dcf",
    learn_more_url: null,
  },
  beta: {
    technical_term: "beta",
    display_label: "Risk (Beta)",
    technical_label: "Beta",
    tooltip:
      "A measure of a stock's volatility relative to the market. A beta of 1 means it moves with the market; above 1 is more volatile.",
    category: "dcf",
    learn_more_url: null,
  },
  equity_risk_premium: {
    technical_term: "equity_risk_premium",
    display_label: "Equity Risk Premium",
    technical_label: "ERP",
    tooltip:
      "The extra return investors demand for holding stocks instead of risk-free government bonds.",
    category: "dcf",
    learn_more_url: null,
  },
  cost_of_equity: {
    technical_term: "cost_of_equity",
    display_label: "Cost of Equity",
    technical_label: "Cost of Equity",
    tooltip:
      "The return shareholders require for investing in the company, calculated as risk-free rate plus beta times equity risk premium.",
    category: "dcf",
    learn_more_url: null,
  },
  cost_of_debt: {
    technical_term: "cost_of_debt",
    display_label: "Cost of Debt",
    technical_label: "Cost of Debt",
    tooltip:
      "The effective interest rate a company pays on its borrowings, adjusted for the tax benefit of interest deductions.",
    category: "dcf",
    learn_more_url: null,
  },
  risk_free_rate: {
    technical_term: "risk_free_rate",
    display_label: "Risk-Free Rate",
    technical_label: "Risk-Free Rate",
    tooltip:
      "The return on a theoretically riskless investment, typically the yield on a 10-year government bond.",
    category: "dcf",
    learn_more_url: null,
  },
  terminal_growth: {
    technical_term: "terminal_growth",
    display_label: "Long-Term Growth Rate",
    technical_label: "Terminal Growth",
    tooltip:
      "The rate at which free cash flow is assumed to grow forever after the forecast period. Usually capped at the economy's growth rate.",
    category: "dcf",
    learn_more_url: null,
  },
  discount_rate: {
    technical_term: "discount_rate",
    display_label: "Discount Rate",
    technical_label: "Discount Rate",
    tooltip:
      "The rate used to convert future cash flows into today's dollars. Higher rates mean future cash flows are worth less today.",
    category: "dcf",
    learn_more_url: null,
  },
  enterprise_value: {
    technical_term: "enterprise_value",
    display_label: "Enterprise Value",
    technical_label: "EV",
    tooltip:
      "The total value of a company's operations: market cap plus debt minus cash. It represents what you would pay to buy the entire business.",
    category: "dcf",
    learn_more_url: null,
  },
  intrinsic_value: {
    technical_term: "intrinsic_value",
    display_label: "Intrinsic Value",
    technical_label: "Intrinsic Value",
    tooltip:
      "The estimated fair value per share based on projected future cash flows, independent of the current market price.",
    category: "dcf",
    learn_more_url: null,
  },

  // ---------------------------------------------------------------------------
  // Ratio terms
  // ---------------------------------------------------------------------------
  pe_ratio: {
    technical_term: "pe_ratio",
    display_label: "Price-to-Earnings",
    technical_label: "P/E",
    tooltip:
      "Share price divided by earnings per share. Shows how much investors pay for each dollar of profit. Lower can mean cheaper.",
    category: "ratios",
    learn_more_url: null,
  },
  pb_ratio: {
    technical_term: "pb_ratio",
    display_label: "Price-to-Book",
    technical_label: "P/B",
    tooltip:
      "Share price divided by book value per share. Compares market value to the accounting value of assets minus liabilities.",
    category: "ratios",
    learn_more_url: null,
  },
  debt_to_equity: {
    technical_term: "debt_to_equity",
    display_label: "Debt-to-Equity",
    technical_label: "D/E",
    tooltip:
      "Total debt divided by shareholders' equity. Measures how much the company relies on borrowing versus owner investment.",
    category: "ratios",
    learn_more_url: null,
  },
  current_ratio: {
    technical_term: "current_ratio",
    display_label: "Current Ratio",
    technical_label: "Current Ratio",
    tooltip:
      "Current assets divided by current liabilities. A ratio above 1 means the company can cover its short-term obligations.",
    category: "ratios",
    learn_more_url: null,
  },
  roe: {
    technical_term: "roe",
    display_label: "Return on Equity",
    technical_label: "ROE",
    tooltip:
      "Net income divided by shareholders' equity. Shows how effectively the company uses shareholder money to generate profit.",
    category: "ratios",
    learn_more_url: null,
  },
  roa: {
    technical_term: "roa",
    display_label: "Return on Assets",
    technical_label: "ROA",
    tooltip:
      "Net income divided by total assets. Measures how efficiently the company uses all its assets to generate profit.",
    category: "ratios",
    learn_more_url: null,
  },
  gross_margin: {
    technical_term: "gross_margin",
    display_label: "Gross Margin",
    technical_label: "Gross Margin",
    tooltip:
      "Revenue minus cost of goods sold, divided by revenue. Shows what percentage of sales is left after direct production costs.",
    category: "ratios",
    learn_more_url: null,
  },
  operating_margin: {
    technical_term: "operating_margin",
    display_label: "Operating Margin",
    technical_label: "Operating Margin",
    tooltip:
      "Operating income divided by revenue. Shows what percentage of sales remains after all operating expenses.",
    category: "ratios",
    learn_more_url: null,
  },
  net_margin: {
    technical_term: "net_margin",
    display_label: "Net Margin",
    technical_label: "Net Margin",
    tooltip:
      "Net income divided by revenue. The bottom-line profitability after all expenses, taxes, and interest.",
    category: "ratios",
    learn_more_url: null,
  },

  // ---------------------------------------------------------------------------
  // Profile terms
  // ---------------------------------------------------------------------------
  market_cap: {
    technical_term: "market_cap",
    display_label: "Market Cap",
    technical_label: "Market Capitalization",
    tooltip:
      "Share price multiplied by total shares outstanding. Represents the total market value of the company's equity.",
    category: "profile",
    learn_more_url: null,
  },
  dividend_yield: {
    technical_term: "dividend_yield",
    display_label: "Dividend Yield",
    technical_label: "Dividend Yield",
    tooltip:
      "Annual dividend per share divided by the share price. Shows how much cash income you receive relative to the stock's price.",
    category: "profile",
    learn_more_url: null,
  },
  shares_outstanding: {
    technical_term: "shares_outstanding",
    display_label: "Shares Outstanding",
    technical_label: "Shares Outstanding",
    tooltip:
      "The total number of shares currently held by all shareholders, including insiders and institutions.",
    category: "profile",
    learn_more_url: null,
  },
  ttm: {
    technical_term: "ttm",
    display_label: "Trailing Twelve Months",
    technical_label: "TTM",
    tooltip:
      "The sum of the last four quarters of data. Gives a rolling annual view that is more current than the last fiscal year.",
    category: "profile",
    learn_more_url: null,
  },
};

/**
 * Look up a glossary entry by its technical term key.
 */
export function getGlossaryEntry(term: string): GlossaryEntry | undefined {
  return glossary[term];
}
